# Generated by Django 3.0.2 on 2020-02-10 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subcriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('subemail', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'subscriber',
            },
        ),
    ]
