# Generated by Django 3.0.2 on 2020-02-10 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_subcriber'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('adminname', models.CharField(max_length=100)),
                ('adminemail', models.CharField(max_length=100)),
                ('adminpassword', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'adminuser',
            },
        ),
    ]
